language: en-US
tone_instructions: "Be concise and focus on critical issues only"
reviews:
  docs:
    enabled: true
  profile: assertive
  commit_status: true
  fail_commit_status: true
  auto_review:
    enabled: true
    drafts: false
  tools:
    eslint:
      enabled: true
      # Point to a repository-level ESLint config so this static file can be resolved
      config_file: .eslintrc.json
    ruff:
      enabled: true
      config_file: pyproject.toml # or ruff.toml if you split it
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "docs/mergekit/**/*.md"
      - "docs/**/*.md"
