language: en-US
tone_instructions: "Be concise and focus on critical issues only"
reviews:
  docs:
    enabled: true
  profile: assertive
  commit_status: true
  fail_commit_status: true
  auto_review:
    enabled: true
    drafts: false
  tools:
    eslint:
      enabled: true
      config_file: templates/{{project_slug}}/.eslintrc.cjs   # adjust to actual path
    ruff:
      enabled: true
      config_file: pyproject.toml   # or ruff.toml if you split it
knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "docs/mergekit/**/*.md"
      - "docs/**/*.md"
