name: 'Setup Devbox'
description: 'Install and cache Devbox with retry logic'
inputs:
  skip:
    description: 'Skip installation'
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Cache Devbox binary
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ~/.local/bin/devbox
        key: devbox-${{ runner.os }}-${{ hashFiles('devbox.lock') }}
    - name: Install Devbox
      if: inputs.skip != 'true'
      shell: bash
      run: |
        if command -v devbox &>/dev/null; then
          echo "Devbox already installed"
          devbox version
          exit 0
        fi
        for i in {1..3}; do
          if curl -fsSL https://get.jetpack.io/devbox | bash -s -- -f; then
            echo "$HOME/.local/bin" >> $GITHUB_PATH
            devbox version
            exit 0
          fi
          echo "Retry $i/3 failed, waiting..."
          sleep $((i * 2))
        done
        echo "::error::Failed to install Devbox after 3 attempts"
        exit 1
