/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ServiceGeneratorOptions {
  /**
   * Name of the service to scaffold
   */
  name: string;
  /**
   * Programming language for the service
   */
  language?: 'python' | 'typescript';
  [k: string]: unknown;
}
