/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for generating backend services with hexagonal architecture
 */
export interface ServiceGeneratorOptions {
  /**
   * Name of the service to scaffold (kebab-case)
   */
  name: string;
  /**
   * Programming language for the service
   */
  language?: 'python' | 'typescript';
  /**
   * Custom directory for the service (relative to apps/)
   */
  directory?: string;
  [k: string]: unknown;
}
