/**
 * @file Utilities for loading and interacting with the resolved tech stack configuration.
 * @author Jules
 *
 * @description
 * This module provides functions to safely load and parse the `techstack.resolved.json` file,
 * which is generated by the `translator.py` script. This JSON file contains a structured
 * representation of the project's technology stack, including languages, frameworks, and tools.
 * These utilities are used by Nx generators to make decisions based on the project's specific
 * technology choices.
 */

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Loads and parses the resolved tech stack JSON file from its expected location.
 *
 * This function looks for `techstack.resolved.json` in a default directory:
 * `<project-root>/tools/transformers/.derived/`. The path can be overridden by setting the
 * `VIBEPDK_TECHSTACK_RESOLVED` environment variable.
 *
 * It handles file system errors gracefully. If the file doesn't exist or an error occurs
 * during reading or parsing, it returns `null` instead of throwing an error.
 *
 * @param {string} root - The root directory of the project. This is used to construct the
 *   default path to the resolved tech stack file.
 * @returns {unknown | null} The parsed JSON object from the tech stack file if successful;
 *   otherwise, `null`. The return type is `unknown` because the file content is externally
- *   generated and cannot be fully trusted without validation.
 */
export function loadResolvedStack(root: string): unknown | null {
  const override = process.env.VIBEPDK_TECHSTACK_RESOLVED;
  const p = override || join(root, 'tools', 'transformers', '.derived', 'techstack.resolved.json');
  if (!existsSync(p)) {
    return null;
  }
  try {
    const txt = readFileSync(p, 'utf8');
    return JSON.parse(txt);
  } catch (_e) {
    // Gracefully handle JSON parsing errors or other file read issues.
    return null;
  }
}

/**
 * Retrieves a specific category object from a parsed tech stack configuration.
 *
 * This is a safe accessor function that checks for the existence of the `categories`
 * property and the specific category key before attempting to access it, preventing
 * runtime errors.
 *
 * @param {any} stack - The parsed tech stack object, typically the return value from `loadResolvedStack`.
 *   It is of type `any` to accommodate the `unknown` return from the loader.
 * @param {string} key - The key of the category to retrieve (e.g., 'frontend', 'backend').
 * @returns {any | null} The value of the category if it exists; otherwise, `null`.
 */
export function getCategory(stack: any, key: string): any | null {
  if (!stack || !stack.categories || !stack.categories[key]) {
    return null;
  }
  return stack.categories[key];
}

/**
 * @interface TechStack
 * @description Defines the expected structure of the resolved tech stack JSON object.
 * This interface is used for type safety within TypeScript code that consumes the
 * tech stack configuration.
 */
export interface TechStack {
  /**
   * @property {Record<string, string>} categories - A map where keys are category names
   * (e.g., 'ci', 'database') and values are the specific technologies chosen for that category.
   */
  categories: Record<string, string>;

  /**
   * @property {string[]} frameworks - An array of strings, listing all the frameworks
   * used in the project (e.g., 'react', 'express').
   */
  frameworks: string[];

  /**
   * @property {string[]} languages - An array of strings, listing the programming languages
   * used (e.g., 'typescript', 'python').
   */
  languages: string[];

  /**
   * @property {string[]} tools - An array of strings, listing the development and operational
   * tools used (e.g., 'jest', 'docker').
   */
  tools: string[];
}
