#!/usr/bin/env bash
# ============================================================================
# VibesPro Environment Setup for GUI Applications
# ============================================================================
# This script sets up environment variables for GUI applications (like VS Code)
# that are launched from the desktop and don't inherit shell environment.
#
# Installation Options:
#
# Option 1: Add to ~/.profile (affects all login sessions)
#   echo 'source ~/projects/VibesPro/scripts/setup/gui-env-setup.sh' >> ~/.profile
#
# Option 2: Add to ~/.pam_environment (PAM-based, most reliable)
#   MISE_SHIMS=${HOME}/.local/share/mise/shims
#   PATH DEFAULT=${MISE_SHIMS}:${HOME}/.local/bin:${PATH}
#
# Option 3: Create systemd user environment (modern systemd systems)
#   Run: ./scripts/setup/gui-env-setup.sh --install-systemd
#
# Option 4: Add to ~/.config/environment.d/50-mise.conf (systemd user)
#   PATH=${HOME}/.local/share/mise/shims:${HOME}/.local/bin:${PATH}
#
# Traceability: AI_ADR-001, DEV-SDS-018
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ============================================================================
# Helper Functions
# ============================================================================

add_to_path() {
  local dir="$1"
  if [[ -d "${dir}" ]] && [[ ":${PATH}:" != *":${dir}:"* ]]; then
    export PATH="${dir}:${PATH}"
  fi
}

# ============================================================================
# Environment Setup
# ============================================================================

setup_mise_paths() {
  # Add mise shims (version-aware tool wrappers)
  add_to_path "${HOME}/.local/share/mise/shims"

  # Add mise bin directory
  add_to_path "${HOME}/.local/bin"

  # Add cargo bin for Rust tools
  add_to_path "${HOME}/.cargo/bin"
}

# ============================================================================
# Installation Functions
# ============================================================================

install_systemd_user_env() {
  local env_dir="${HOME}/.config/environment.d"
  local env_file="${env_dir}/50-vibespro.conf"

  mkdir -p "${env_dir}"

  cat >"${env_file}" <<'EOF'
# VibesPro Environment Configuration
# This file ensures mise tools are available to GUI applications
# Generated by: scripts/setup/gui-env-setup.sh

PATH=${HOME}/.local/share/mise/shims:${HOME}/.local/bin:${HOME}/.cargo/bin:${PATH}
MISE_SHELL=bash
EOF

  echo "✅ Created ${env_file}"
  echo ""
  echo "To apply changes, either:"
  echo "  1. Log out and back in"
  echo "  2. Run: systemctl --user import-environment PATH"
  echo ""
}

install_xdg_autostart() {
  local autostart_dir="${HOME}/.config/autostart"
  local desktop_file="${autostart_dir}/vibespro-env.desktop"

  mkdir -p "${autostart_dir}"

  cat >"${desktop_file}" <<EOF
[Desktop Entry]
Type=Application
Name=VibesPro Environment
Comment=Sets up mise environment for GUI applications
Exec=/bin/bash -c 'export PATH="\${HOME}/.local/share/mise/shims:\${HOME}/.local/bin:\${PATH}" && systemctl --user import-environment PATH'
Hidden=false
NoDisplay=true
X-GNOME-Autostart-enabled=true
EOF

  echo "✅ Created ${desktop_file}"
  echo "This will run at login to set up the environment."
}

show_profile_snippet() {
  echo "Add the following to your ~/.profile or ~/.bash_profile:"
  echo ""
  echo "# VibesPro mise environment"
  echo 'export PATH="${HOME}/.local/share/mise/shims:${HOME}/.local/bin:${PATH}"'
  echo 'export MISE_SHELL="bash"'
  echo ""
}

# ============================================================================
# Main Entry Point
# ============================================================================

main() {
  case "${1:-}" in
    --install-systemd)
      install_systemd_user_env
      ;;
    --install-autostart)
      install_xdg_autostart
      ;;
    --show-profile)
      show_profile_snippet
      ;;
    --help | -h)
      echo "Usage: $0 [--install-systemd|--install-autostart|--show-profile]"
      echo ""
      echo "Options:"
      echo "  --install-systemd   Create ~/.config/environment.d/50-vibespro.conf"
      echo "  --install-autostart Create ~/.config/autostart/vibespro-env.desktop"
      echo "  --show-profile      Show snippet to add to ~/.profile"
      echo ""
      echo "Without arguments: sources the environment for the current shell"
      ;;
    *)
      # Default: set up paths for current shell
      setup_mise_paths
      ;;
  esac
}

# Only run main if not being sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
else
  # Being sourced - just set up paths
  setup_mise_paths
fi
