# Auto-generated by gen_py_types.py
# DO NOT EDIT MANUALLY - Regenerate with: just gen-types-py
#
# These Pydantic models correspond to the TypeScript interfaces
# generated from the PostgreSQL database schema.
#
# Note: The TypeScript Database namespace is not generated here
# as it's a TypeScript-specific pattern for Supabase client typing.
from pydantic import BaseModel, JsonValue


class Profiles(BaseModel):
    id: str
    user_id: str
    bio: str | None
    location: str | None
    website_url: str | None
    social_links: dict[str, JsonValue] | None
    preferences: dict[str, JsonValue] | None
    created_at: str
    updated_at: str


class ProjectMembers(BaseModel):
    id: str
    project_id: str
    user_id: str
    role: str | None
    joined_at: str


class Projects(BaseModel):
    id: str
    owner_id: str
    name: str
    description: str | None
    tags: list[str] | None
    status: str | None
    visibility: str | None
    settings: dict[str, JsonValue] | None
    created_at: str
    updated_at: str


class Users(BaseModel):
    id: str
    email: str
    created_at: str
    updated_at: str
    is_active: bool
    display_name: str | None
    avatar_url: str | None
    metadata: dict[str, JsonValue] | None
