# Auto-generated by gen_py_types.py
from pydantic import BaseModel
import typing


class Profiles(BaseModel):
    id: str
    user_id: str
    bio: typing.Optional[str]
    location: typing.Optional[str]
    website_url: typing.Optional[str]
    social_links: typing.Optional[dict[str, typing.Any]]
    preferences: typing.Optional[dict[str, typing.Any]]
    created_at: str
    updated_at: str
class ProjectMembers(BaseModel):
    id: str
    project_id: str
    user_id: str
    role: typing.Optional[str]
    joined_at: str
class Projects(BaseModel):
    id: str
    owner_id: str
    name: str
    description: typing.Optional[str]
    tags: typing.Optional[list[str]]
    status: typing.Optional[str]
    visibility: typing.Optional[str]
    settings: typing.Optional[dict[str, typing.Any]]
    created_at: str
    updated_at: str
class Users(BaseModel):
    id: str
    email: str
    created_at: str
    updated_at: str
    is_active: bool
    display_name: typing.Optional[str]
    avatar_url: typing.Optional[str]
    metadata: typing.Optional[dict[str, typing.Any]]
class Database(BaseModel):
    Row: typing.Any
    Insert: typing.Any
    Update: typing.Any
    Views: dict[str, typing.Any]
    Functions: dict[str, typing.Any]
