/**
 * Auto-generated TypeScript types from PostgreSQL database schema
 * Generated by: tools/scripts/gen_ts_from_pg.py
 * Source: Supabase local development database
 *
 * DO NOT EDIT MANUALLY - Regenerate with: just gen-types-ts
 * DEV-SDS-020: End-to-End Type Safety Pipeline
 */

/* eslint-disable @typescript-eslint/no-explicit-any */

/**
 * Database table: profiles
 * Auto-generated from PostgreSQL schema
 */
export interface Profiles {
  id: string;
  user_id: string;
  bio: string | null;
  location: string | null;
  website_url: string | null;
  social_links: Record<string, unknown> | null;
  preferences: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
}
/**
 * Database table: project_members
 * Auto-generated from PostgreSQL schema
 */
export interface ProjectMembers {
  id: string;
  project_id: string;
  user_id: string;
  role: string | null;
  joined_at: string;
}
/**
 * Database table: projects
 * Auto-generated from PostgreSQL schema
 */
export interface Projects {
  id: string;
  owner_id: string;
  name: string;
  description: string | null;
  tags: string[] | null;
  status: string | null;
  visibility: string | null;
  settings: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
}
/**
 * Database table: users
 * Auto-generated from PostgreSQL schema
 */
export interface Users {
  id: string;
  email: string;
  created_at: string;
  updated_at: string;
  is_active: boolean;
  display_name: string | null;
  avatar_url: string | null;
  metadata: Record<string, unknown> | null;
}

/**
 * Database type namespace for Supabase-style type access
 */
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: Profiles;
        Insert: Partial<Profiles>;
        Update: Partial<Profiles>;
      };
      project_members: {
        Row: ProjectMembers;
        Insert: Partial<ProjectMembers>;
        Update: Partial<ProjectMembers>;
      };
      projects: {
        Row: Projects;
        Insert: Partial<Projects>;
        Update: Partial<Projects>;
      };
      users: {
        Row: Users;
        Insert: Partial<Users>;
        Update: Partial<Users>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
  };
}
