name: MarkdownLint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false

      - name: Run markdownlint
        run: pnpm dlx markdownlint-cli@0.36.0 "**/*.md" --config .markdownlint.json
