# Node Tests - Unit Tests and Code Quality Checks
#
# This workflow runs Node.js unit tests and various linting checks including:
# - Node.js unit tests (test:node)
# - Shell script linting with ShellCheck (lint:shell)
# - Markdown linting with markdownlint (lint:md)
#
# Environment Variables:
# - NODE_ENV: Set to 'test' during CI runs
#
# Traceability: AI_ADR-005, AI_PRD-005, AI_SDS-004, AI_TS-004

name: Node Tests

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: '20'

      - name: Run unit tests (Node)
        run: pnpm run test:node

  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: '20'

      - name: Run shellcheck
        run: pnpm run lint:shell

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: '20'

      - name: Run markdownlint
        run: pnpm run lint:md
