/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for the meta-generator that scaffolds new Nx generators
 */
export type GeneratorGeneratorOptions = {
  [k: string]: unknown;
} & {
  /**
   * Name of the generator to create (kebab-case)
   */
  name: string;
  /**
   * Type of generator to create, determines default template patterns
   */
  type?: 'domain' | 'service' | 'component' | 'adapter' | 'utility' | 'custom';
  /**
   * Human-readable description of what this generator creates
   */
  description?: string;
  /**
   * Directory within generators/ to place this generator
   */
  directory?: string;
  /**
   * Default target scope for generated projects
   */
  targetScope?: 'apps' | 'libs' | 'tools';
  /**
   * Include externalSchematic() composition pattern for calling other Nx generators
   */
  withComposition?: boolean;
  /**
   * Comma-separated list of Nx generators to compose (e.g., '@nx/js:lib,@nx/react:component')
   */
  compositionGenerators?: string;
  /**
   * Include hexagonal architecture patterns (domain/application/infrastructure layers)
   */
  withHexagonal?: boolean;
  /**
   * Generate test scaffold for the generator
   */
  withTests?: boolean;
  /**
   * Generate a GENERATOR_SPEC.md documentation file
   */
  withSpec?: boolean;
  /**
   * Comma-separated default tags for generated projects
   */
  tags?: string;
  [k: string]: unknown;
};
